
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      ‘Ў®аЄ  ­ з в  29.02.2024 0:11:14.
      
      Џа®ҐЄв "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.55
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      ‘Ў®аЄ  ­ з в  29.02.2024 0:11:15.
      
      Џа®ҐЄв "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.39
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-txwb7x"
      binary: "C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-txwb7x"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-txwb7x'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_afa6c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.6.3+07e294721 for .NET Framework
        ‘Ў®аЄ  ­ з в  29.02.2024 0:11:16.
        
        Џа®ҐЄв "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-txwb7x\\cmTC_afa6c.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_afa6c.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-txwb7x\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_afa6c.dir\\Debug\\cmTC_afa6c.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_afa6c.dir\\Debug\\cmTC_afa6c.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_afa6c.dir\\Debug\\\\" /Fd"cmTC_afa6c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.36.32537 ¤«п x64
          CMakeCCompilerABI.c
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_afa6c.dir\\Debug\\\\" /Fd"cmTC_afa6c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-txwb7x\\Debug\\cmTC_afa6c.exe" /INCREMENTAL /ILK:"cmTC_afa6c.dir\\Debug\\cmTC_afa6c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-txwb7x/Debug/cmTC_afa6c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-txwb7x/Debug/cmTC_afa6c.lib" /MACHINE:X64  /machine:x64 cmTC_afa6c.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_afa6c.vcxproj -> C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-txwb7x\\Debug\\cmTC_afa6c.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_afa6c.dir\\Debug\\cmTC_afa6c.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_afa6c.dir\\Debug\\cmTC_afa6c.tlog\\cmTC_afa6c.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-txwb7x\\cmTC_afa6c.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.38
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-3j23v7"
      binary: "C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-3j23v7"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-3j23v7'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_b2380.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.6.3+07e294721 for .NET Framework
        ‘Ў®аЄ  ­ з в  29.02.2024 0:11:17.
        
        Џа®ҐЄв "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-3j23v7\\cmTC_b2380.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_b2380.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-3j23v7\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_b2380.dir\\Debug\\cmTC_b2380.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_b2380.dir\\Debug\\cmTC_b2380.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b2380.dir\\Debug\\\\" /Fd"cmTC_b2380.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.36.32537 ¤«п x64
          CMakeCXXCompilerABI.cpp
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b2380.dir\\Debug\\\\" /Fd"cmTC_b2380.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-3j23v7\\Debug\\cmTC_b2380.exe" /INCREMENTAL /ILK:"cmTC_b2380.dir\\Debug\\cmTC_b2380.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-3j23v7/Debug/cmTC_b2380.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/kypri/source/repos/proglab1-23-24/NewRes2/CMakeFiles/CMakeScratch/TryCompile-3j23v7/Debug/cmTC_b2380.lib" /MACHINE:X64  /machine:x64 cmTC_b2380.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_b2380.vcxproj -> C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-3j23v7\\Debug\\cmTC_b2380.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_b2380.dir\\Debug\\cmTC_b2380.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_b2380.dir\\Debug\\cmTC_b2380.tlog\\cmTC_b2380.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "C:\\Users\\kypri\\source\\repos\\proglab1-23-24\\NewRes2\\CMakeFiles\\CMakeScratch\\TryCompile-3j23v7\\cmTC_b2380.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.39
        
      exitCode: 0
...
